<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.18.0" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.73.0.4053" />
    <PackageReference Include="Google.GenAI" Version="1.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="assets\characters\*.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
